server:
  port: 8302

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zhpb_stores?characterEncoding=utf-8&useSSL=false
    username: root
    password: "1767737316."

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: com/stdu/zhpb/store/mapper/xml/*.xml
