server:
  port: 8301

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zhpb_employees?characterEncoding=utf-8&useSSL=false
    username: root
    password: "1767737316."

  application:
    name: service-employee

  cloud:
    nacos:
      server-addr: 127.0.0.1:8848

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

